### ISSUE TITLE
which qt3d version and qt version can build and run 3ddashboard??

### ISSUE THREAD

**Issue by jordonwu** [Airtau/3dDashBoard#1]
which qt3d version and qt version can build and run 3ddashboard? thanks

**Comment by Airtau** [comment]
Dear friend,

it works with QT 5.2+qt3d v.1. I will adapt this for QT5.5 in next month.

Regards,
Aleksandr.

**Comment by jordonwu** [comment]
Hi Airtau,
Got it. I'm a newbie to study qt3d and qml. expect your qt5.5 example to study it. thanks
